### ISSUE TITLE
iat support

### ISSUE THREAD

**Issue by isysd** [deginner/bitjws#3]
It would be helpful for JWT's iat field to be supported. Flask-bitjws would use this like a nonce https://github.com/deginner/flask-bitjws/issues/4.

**Comment by g-p-g** [comment]
Right now you can use it by calling `sign_serialize(iat=something, ...)`. Can you tell more about how bitjws needs to be modified to accommodate for that situation?

**Comment by isysd** [comment]
Ah, I didn't think about that! Thanks, I don't think any change is necessary here. I guess it is more important that the client (i.e. https://github.com/deginner/bravado-bitjws) uses that iat field.

**Comment by g-p-g** [comment]
Right, maybe there could be something to clearly specify JWT claims vs arbitrary payload but in the end they're both arbitrary. I'm closing this but if it becomes clear that some kind of distinction is necessary then we can decide how to implement it at that point.
